version: '3.4'
services:
  api:
    container_name: wallester_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
      - "${APP_PORT}:${APP_PORT}"

  database:
    container_name: wallester_database
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=/var/lib/postgresql/pgdata
    volumes:
      - wallester-database:/var/lib/postgresql/data
      - ./pgdata:/docker-entrypoint-initdb.d
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  adminer:
    container_name: wallester_adminer
    image: adminer
    depends_on:
      - database
    environment:
      - ADMINER_DEFAULT_SERVER=${DATABASE_HOST}
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  wallester-database:
